package bracketgenerator;

import java.util.List;

public interface Generator {
    /**
     * Generates a list of strings based on the implementation of the generator.
     * The exact generation logic is defined by the classes implementing this interface.
     *
     * @return a list of strings generated by the implementing class.
     *         The content of the list depends on the specific logic of the generator.
     */
    List<String> generate();
}
